name: Setup CUDA on Windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup-cuda:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone setup_cuda repository
        run: git clone https://github.com/Silverlan/setup_cuda.git

      - name: Setup CUDA Toolkit
        id: cuda-toolkit
        shell: pwsh
        run: scripts/setup_cuda.ps1
        env:
            INPUT_CUDA_VERSION: "v12.5.0"
